import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone1415ProMax1(),
        ]),
      ),
    );
  }
}

class Iphone1415ProMax1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 18,
                top: 513,
                child: Container(
                  width: 391,
                  height: 153,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x0F000000),
                        blurRadius: 4,
                        offset: Offset(0, 1),
                        spreadRadius: 5,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 34,
                child: Container(
                  width: 44,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xFF3D68FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 34,
                child: Container(
                  width: 44,
                  height: 44,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/44x44"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(
                      side: BorderSide(width: 1, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 435,
                child: Container(
                  width: 44,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Color(0xEDEBE6E6),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 449,
                child: Text(
                  'JN',
                  style: TextStyle(
                    color: Color(0xFF08D635),
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 51,
                top: 265,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF11C759),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 552,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF11C759),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 552,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF11C759),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 552,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF140344),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 335,
                top: 552,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF66A1E7),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 136,
                top: 265,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF3D68FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 224,
                top: 265,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE23A3A),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 318,
                top: 265,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF26CAFF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 37,
                child: SizedBox(
                  width: 111,
                  height: 46,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Good Evening',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 14,
                            fontFamily: 'Barlow',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: ',\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Barlow',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'JOHN',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Barlow',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 113,
                child: Container(
                  width: 391,
                  height: 104,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Colors.white),
                      borderRadius: BorderRadius.circular(30),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 4,
                        offset: Offset(0, 1),
                        spreadRadius: 3,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 176,
                top: 118,
                child: Text(
                  'Balance',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w200,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 119,
                top: 139,
                child: SizedBox(
                  width: 161,
                  height: 46,
                  child: Text(
                    'Ksh. 5,300.98',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 30,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w275,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111,
                top: 179,
                child: Text(
                  'Available FULIZA: KSH 5,000.00',
                  style: TextStyle(
                    color: Color(0xFF5F79FF),
                    fontSize: 15,
                    fontFamily: 'Barlow Semi Condensed',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 324,
                child: SizedBox(
                  width: 63,
                  height: 41,
                  child: Text(
                    'SEND AND \nREQUEST',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 609,
                child: SizedBox(
                  width: 68,
                  height: 22,
                  child: Text(
                    'GLOBALPAY',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 125,
                top: 608,
                child: SizedBox(
                  width: 68,
                  height: 22,
                  child: Text(
                    'M-SHWARI',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 224,
                top: 608,
                child: SizedBox(
                  width: 68,
                  height: 22,
                  child: Text(
                    'KCB M-PESA',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 347,
                top: 608,
                child: SizedBox(
                  width: 33,
                  height: 22,
                  child: Text(
                    'MALI',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 432,
                child: SizedBox(
                  width: 116,
                  height: 17,
                  child: Text(
                    'JAMES NDUNG’U',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 453,
                child: SizedBox(
                  width: 95,
                  height: 17,
                  child: Text(
                    '0704***969',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w300,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 342,
                top: 431,
                child: SizedBox(
                  width: 88,
                  height: 17,
                  child: Text(
                    '- KSH. 50.00',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 324,
                top: 452,
                child: SizedBox(
                  width: 95,
                  height: 17,
                  child: Text(
                    '8 Oct, 08:09 PM',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w300,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 400,
                child: SizedBox(
                  width: 126,
                  height: 24,
                  child: Text(
                    'MPESA STATEMENTS',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 371,
                top: 400,
                child: SizedBox(
                  width: 54,
                  height: 24,
                  child: Text(
                    'SEE ALL',
                    style: TextStyle(
                      color: Color(0xFF10C659),
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 342,
                top: 523,
                child: SizedBox(
                  width: 67,
                  height: 29,
                  child: Text(
                    'View All',
                    style: TextStyle(
                      color: Color(0xFF10C659),
                      fontSize: 19,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 324,
                top: 324,
                child: SizedBox(
                  width: 48,
                  height: 20,
                  child: Text(
                    'AIRTIME',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 222,
                top: 324,
                child: SizedBox(
                  width: 63,
                  height: 41,
                  child: Text(
                    'WITHDRAW',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 149,
                top: 324,
                child: SizedBox(
                  width: 28,
                  height: 20,
                  child: Text(
                    'PAY',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 523,
                child: SizedBox(
                  width: 143,
                  height: 23,
                  child: Text(
                    'Financial Services',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 19,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 709,
                child: Container(
                  width: 391,
                  height: 153,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x0F000000),
                        blurRadius: 4,
                        offset: Offset(0, 1),
                        spreadRadius: 5,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 748,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF0544A),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 748,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 748,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.81, 0.58),
                      end: Alignment(-0.81, -0.58),
                      colors: [Color(0xFF140344), Color(0x00140344)],
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 335,
                top: 748,
                child: Container(
                  width: 48,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFF66A1E7),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 805,
                child: SizedBox(
                  width: 63,
                  height: 39,
                  child: Text(
                    'BUY GIFT VOUCHERS',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 125,
                top: 804,
                child: SizedBox(
                  width: 68,
                  height: 22,
                  child: Text(
                    'SHOP ZETU',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 237,
                top: 804,
                child: SizedBox(
                  width: 68,
                  height: 22,
                  child: Text(
                    'EZAWADI',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 330,
                top: 805,
                child: SizedBox(
                  width: 68,
                  height: 30,
                  child: Text(
                    'SAFARICOM MASOKO',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 342,
                top: 719,
                child: SizedBox(
                  width: 67,
                  height: 29,
                  child: Text(
                    'View All',
                    style: TextStyle(
                      color: Color(0xFF10C659),
                      fontSize: 19,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 719,
                child: SizedBox(
                  width: 143,
                  height: 23,
                  child: Text(
                    'Shop & Gift',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 19,
                      fontFamily: 'Barlow Semi Condensed',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
